apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: geetopod-client-example-purephp
    name: geetopod-client-example-purephp
  name: geetopod-client-example-purephp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geetopod-client-example-purephp
      name: geetopod-client-example-purephp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: geetopod-client-example-purephp
        name: geetopod-client-example-purephp
    spec:
      containers:
      - image: gcr.io/geetopod/geetopod-client-example-purephp:0.1.1
        imagePullPolicy: Always
        name: geetopod-client-example-purephp

        ports:
        - containerPort: 80
          protocol: TCP

        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: geetopod-client-example-purephp
  namespace: default
spec:
  ports:
  - name: geetopod-client-example-purephp-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: geetopod-client-example-purephp
    name: geetopod-client-example-purephp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
